### ISSUE TITLE
Submission Info

### ISSUE THREAD

**Issue by eguidotti** [Milano-R/erum2020-covidr-contest#26]
First of all, congratulations for your contest, this is a great initiative!

I would like to submit the following project:
https://github.com/covid19datahub/COVID19
How should I include multiple authors in the .yml file? Comma separated names? 
I couldn't get this information from your docs and video, sorry for bothering.

Thanks!

**Comment by riccardoporreca** [comment]
@emanuele-guidotti, thanks for your interest in CovidR!

The `author` filed is in fact a free-text input that we do not parse in a special way. Comma-separated authors are probable the best way to specify multiple authors.

**Comment by riccardoporreca** [comment]
We are also improving the example in the instructions to help future contributors based on your input.

**Comment by eguidotti** [comment]
Great thank you!
